### ISSUE TITLE
SignPortal to b:mybed

### ISSUE THREAD

**Issue by smbarbour** [Multiverse/Multiverse-SignPortals#21]
It does not happen to everyone (it works fine for myself), but for at least one user, using a SignPortal with the destination of b:mybed teleports her to approx 10 blocks below her bed (into solid block).  Doing an /mvtp b:mybed works without issues for her, but the SignPortal will always teleport incorrectly.

**Comment by OpticFusion1** [comment]
If for some reason this is still an issue, make a new issue here https://github.com/OpticFusion1/Multiverse-SignPortals <3 I'm making and keeping this plugin up to date
