### ISSUE TITLE
Redstone teleporting doesn't work.

### ISSUE THREAD

**Issue by catdadcode** [Multiverse/Multiverse-SignPortals#37]
I've tried implementing the sign portal that teleports entities in an area when it receives a redstone signal. However I cannot get it to work at all. Regular sign portals work fine. It's only the redstone teleporting signs that don't work. [The wiki article](https://github.com/Multiverse/Multiverse-SignPortals/wiki/RedstoneTeleporting) isn't very clear about how to format the sign text. I wish there was a screen shot.

Here are the configurations I've tried so far:

![](http://i.imgur.com/FP2K40X.png)

![](http://i.imgur.com/v8Sm65a.png)
^^ This one simply works as a regular sign portal that you right-click. It just ignores the text at the top of the sign.

![](http://i.imgur.com/PxV8tFu.png)

I'm not sure what other ways to try formatting the sign. I sort of think it just doesn't work and not enough people use it for it to matter. If anyone can recommend me a better plugin for redstone-activated teleporting then please link me :)

**Comment by zax71** [comment]
Upon looking in to this it must be powered from the front. The attatched image works
![image](https://github.com/Multiverse/Multiverse-SignPortals/assets/67716263/21b2af7a-88a7-4327-83b0-4835e4efb2f8)

**Comment by catdadcode** [comment]
😂

**Comment by zax71** [comment]
xD I was looking in to #94 and came across it
