### ISSUE TITLE
Sign Portals incompatible with WorldEdit 6.x

### ISSUE THREAD

**Issue by Rocologo** [Multiverse/Multiverse-SignPortals#39]
Each time i mark a region with worldedit and the try to create a protal with /mvp create portalname i get an error, so its not possible to create portals using WorldEdit 6.x

**Comment by FernFerret** [comment]
I bet this issue was filed under the wrong tracker. There are actually [no commands](https://github.com/Multiverse/Multiverse-SignPortals/wiki/Command-reference) for SignPortals.

You probably wanted [Multiverse-Portals](https://github.com/Multiverse/Multiverse-Portals/wiki). Closing.
