### ISSUE TITLE
Nether portal brings me to edge of world instead of spawn

### ISSUE THREAD

**Issue by freakyy85** [Multiverse/Multiverse-SignPortals#40]
Hi.

The plugin when putting a sign on a nether portal, instead of bringing me to spawn of world_realistic in this case, brings me to edge of world and teleports me somewhere after. I'm using hte latest dev versio on 1.9. The sign then turns blue. I see the spawn, then suddenly it tells me im at the edge of the world. Using signs only it works.

**Comment by OpticFusion1** [comment]
Try this again and if this still happens make an issue here https://github.com/OpticFusion1/Multiverse-SignPortals/ I'm updating the MultiversePlugins <3

**Comment by Jadiction** [comment]
@OpticFusion1 You should consider pull requests or becoming a Multiverse developer/contributor. As of right now, MV is only maintained by one person so new contributors/devs are much welcome.

**Comment by Jadiction** [comment]
Closing ticket because it's years old. Update to the latest versions of Multiverse (Core, Portals and any others you may use). Please open a new ticket if this issue persists or for a faster response, you can also receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
