### ISSUE TITLE
Sign Portal permissions

### ISSUE THREAD

**Issue by etmgs** [Multiverse/Multiverse-SignPortals#47]
Hello,

I have a problem with the Multiverse SignPortal plugin. I, as Operator of my Server, can use the sign and teleport, but my Members, the user, can't use the sign. There is no error message, etc. 
I need help which permission i have to give the players.

Sincerely

etmgs

**Comment by OpticFusion1** [comment]
for future reference, there doesn't seem to be any permission related to using it from as far as i can tell so it was/is probably something else, and it seems like this version of multiverse is dead, a more up to date version can be found here https://github.com/OpticFusion1/Multiverse-SignPortals

**Comment by Jadiction** [comment]
To allow/disallow users from a signportal, you'd deny (or accept) permissions for the world for specific users/groups. This way when they click the signportal, it'll deny them when they do not have world access permission.
