### ISSUE TITLE
Delete any Folder on a Server

### ISSUE THREAD

**Issue by jandie1505** [Multiverse/Multiverse-SignPortals#49]
You can make /mvimport ../ts3
and then
/mvdelete ../ts3
and then your TS is deleted.
More Information: https://youtu.be/7zP5rSAon00
Fix: https://www.spigotmc.org/resources/multiversefix.54316/

**Comment by OpticFusion1** [comment]
That means, the next update i do, this will most likely be fixed <3

**Comment by Jadiction** [comment]
This is a Multiverse-Core issue, and it has been fixed in Multiverse-Core 4.0.x.
