### ISSUE TITLE
Members cannot use sign portals

### ISSUE THREAD

**Issue by Poppycat04** [Multiverse/Multiverse-SignPortals#51]
Hello, I am using a 1.12.2 Bukkit server. 

I have downloaded Multiverse Core latest version, and it works perfectly fine.
I have also downloaded Multiverse Inventories (latest version) and it also works well.
Multiverse sign portals works fine. I am OP on my server, and all of my portal signs are placed in WorldGuard regions where the flag "use" is on allow. As an OP, I can use the signs perfectly back and forth. But my other players cannot. When they right click the signs, nothing happens. Please help me!!!!

Thank you

**Comment by MisterMute** [comment]
I found that giving them permission to multiverse.access* worked for me

**Comment by Jadiction** [comment]
As MisterMute said, they require permission to the world as well. Use `/mv debug 3` to see which permissions they are missing if you are still having issues once giving world access permissions. If you still need help, you can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
