### ISSUE TITLE
New Idea limited by this plugin.

### ISSUE THREAD

**Issue by SadLittleOctopus** [Multiverse/Multiverse-SignPortals#54]
I've been looking to making a massive server which has a main hub, you click a sign or something in a GUI and then you get into your own private world. Your friends can choose to join you if you have the world set to 'open' and maybe friend requesting system could enable 'friends only' worlds. Basically Minecraft Realms, except free and not player limited. The issue with this plugin is that it doesn't have perms that enable creating and going to worlds seperate from the delete and moderate world functions. Any help would be appreciated... thanks!

**Comment by Jadiction** [comment]
I'm sure there are plugins out there that provide a way for users to create their own private world. This wouldn't be a Multiverse feature though.
