### ISSUE TITLE
MV-Signportals Permission use of teleportsigns

### ISSUE THREAD

**Issue by Slyer-9** [Multiverse/Multiverse-SignPortals#80]
Hi, I have a suggestion for MV-Signportals.

Would it be possible to implement a permission to allow/deny using of teleportsigns for special groups/users?

Only members of the group/users with this permission can use teleportsigns.

F.e.: multiverse.signportal.use -> allow/deny             (like already existing: multiverse.signportal.create)

This would be very useful. Thx for answering. 🙂 

br slyer9

Quick remark: Denying the use of signs in general would also affect other plugins like "Chestshop", therefore a special permission for MV-Signportals would be fundamental.

**Comment by Valeros-Jackson** [comment]
Just found this topic,

Same idea. Good suggestion!

**Comment by zax71** [comment]
Implemented in #96, you can grab a dev jar from the [artifacts](https://github.com/Multiverse/Multiverse-SignPortals/actions/runs/8820903125?pr=96) while we wait for code review and release
